name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Calculate NuGet version
      id: version
      uses: paulhatch/semantic-version@v5.0.0-alpha2
      with:
        bump_each_commit: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          5.0.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration $BUILD_CONFIG -p:Version=${{ steps.version.outputs.version }}
    - name: Test
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-build --verbosity normal
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/main')
      run: dotnet nuget push "Euphoric.FluentValidation.AspNetCore\bin\Release\Euphoric.FluentValidation.AspNetCore.*.nupkg" -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}